<html>
<head>
    <title>Our first page!</title>
</head>
<body>
<?php
echo("<h1>Hello World</h1>\n"); //first line generated by PHP
include("include/menu.php");
echo("<p>My first page<br>Now I code with PHP!</p>\n"); //second line of code

/* 
multi-line comment
variables:
*/

$user_name = "John Smith";
$age = 25;
$knows_php = true;
$rating = 1.5;
$preferred_language = "C++";

echo("User name is $user_name<br>\n"); # user name
echo("User age is $age<br>\n");
echo("User knows PHP $knows_php<br>\n");
echo("User's rating is $rating: ");
if ($rating > 7) {
    echo("High<br>\n");
} elseif ($rating <= 7 && $rating > 4) {
    echo("Medium<br>\n");
} else {
    echo("Low<br>\n");
}
echo("Preferred language is $preferred_language: ");
switch($preferred_language) {
    case "PHP":
        echo("Can code backend for websites.<br>\n");
        break;
    case "C++":
        echo("Can code fast software and games.<br>\n");
        break;
    case "HTML":
        echo("Can code frontend for websites.<br>\n");
        break;
    case "Java":
        echo("Can code mobile apps.<br>\n");
        break;
    default:
        echo("Unknown language.");
}

?>
</body>
</html>
